message(STATUS "start check cmake ...")
message(" # cmake")
message("   CMAKE_VERSION               - ${CMAKE_VERSION}")
message("   CMAKE_ROOT                  - ${CMAKE_ROOT}")
message(" # generator")
message("   CMAKE_GENERATOR             - ${CMAKE_GENERATOR}")
message("   CMAKE_GENERATOR_PLATFORM    - ${CMAKE_GENERATOR_PLATFORM}")
message("   CMAKE_GENERATOR_TOOLSET     - ${CMAKE_GENERATOR_TOOLSET}")
message(" # project")
message("   PROJECT_NAME                - ${PROJECT_NAME}")
message("   PROJECT_VERSION             - ${PROJECT_VERSION}")
message("   PROJECT_VERSION_MAJOR       - ${PROJECT_VERSION_MAJOR}")
message("   PROJECT_VERSION_MINOR       - ${PROJECT_VERSION_MINOR}")
message("   PROJECT_VERSION_PATCH       - ${PROJECT_VERSION_PATCH}")
message("   PROJECT_VERSION_TWEAK       - ${PROJECT_VERSION_TWEAK}")
message("   PROJECT_SOURCE_DIR          - ${PROJECT_SOURCE_DIR}")
message("   PROJECT_BINARY_DIR          - ${PROJECT_BINARY_DIR}")
message(" # configure")
message("   CMAKE_CONFIGURATION_TYPES   - ${CMAKE_CONFIGURATION_TYPES}")
message("   CMAKE_BUILD_TYPE            - ${CMAKE_BUILD_TYPE}")
message(" # system")
message("   CMAKE_HOST_WIN32            - ${CMAKE_HOST_WIN32}")
message("   CMAKE_HOST_UNIX             - ${CMAKE_HOST_UNIX}")
message("   CMAKE_HOST_APPLE            - ${CMAKE_HOST_APPLE}")
message("   CMAKE_HOST_SYSTEM_NAME      - ${CMAKE_HOST_SYSTEM_NAME}")
message("   CMAKE_HOST_SYSTEM_PROCESSOR - ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message("   CMAKE_HOST_SYSTEM_VERSION   - ${CMAKE_HOST_SYSTEM_VERSION}")
message("   CMAKE_SYSTEM                - ${CMAKE_SYSTEM}")
message("   CMAKE_SYSTEM_NAME           - ${CMAKE_SYSTEM_NAME}")
message("   CMAKE_SYSTEM_PROCESSOR      - ${CMAKE_SYSTEM_PROCESSOR}")
message("   CMAKE_SYSTEM_VERSION        - ${CMAKE_SYSTEM_VERSION}")
message(" # compiler")
message("   XCODE_VERSION               - ${XCODE_VERSION}")
message("   MSVC_VERSION                - ${MSVC_VERSION}")
message("   MSVC_IDE                    - ${MSVC_IDE}")
message("   MSVC                        - ${MSVC}")
message(" # environment var")
message("   ENV{COMPUTERNAME}           - $ENV{COMPUTERNAME}")
message("   ENV{USERNAMA}               - $ENV{USERNAME}")
message(STATUS "check cmake ended .")
